import "./globals.css";

export const metadata = {
  title: "Product Shop",
  description: "Generated by Erfan Hosseini",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f2f2f2]">{children}</body>
    </html>
  );
}
